project:
  type: website
  output-dir: docs

website:
  title: "mylesowens"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: Substack
        href: https://mylesowens.substack.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/myles-owens/
        aria-label: LinkedIn

format:
  html:
    theme: none
    css: styles.css
    toc: true

editor: visual
